spring:
  application:
    name: notification-service

  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
#      retries: 10
      properties:
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
        enable.idempotence: true
        max.in.flight.per.connection: 5
#        retry.backoff.ms: 500

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/clients_db
    username: postgres
    password: postgres

  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath*:database/initDB.sql


server:
  port: 8080
