CREATE TABLE IF NOT EXISTS Clients (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    email varchar NOT NULL,
    age int check ( age < 150) check ( age > -1 ),
    created_at TIMESTAMP DEFAULT now()
);